---
title: DIST
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: support@greenweb.org
description: The Digital Impacts Schema and Taxonomy
domain: dist.greenweb.org
baseurl: ''
url: https://dist.greenweb.org
theme: minima
plugins:
- jekyll-feed
